const J=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json","cache-control":"no-store"}});
const clean=r=>r&&({device_id:r.device_id,name:r.name,room:r.room,status:r.status,mode:r.mode,target_temp:r.target_temp,temperature:r.temperature,humidity:r.humidity,co2:r.co2,recorded_at:r.recorded_at});
const latest=(db,id)=>db.prepare(`SELECT d.device_id,d.name,d.room,d.status,d.mode,d.target_temp,r.temperature,r.humidity,r.co2,r.recorded_at FROM devices d LEFT JOIN sensor_readings r ON r.id=(SELECT id FROM sensor_readings x WHERE x.device_id=d.device_id ORDER BY x.id DESC LIMIT 1) WHERE d.device_id=?`).bind(id).first();
export default {async fetch(req,env){const u=new URL(req.url);try{
if(u.pathname==='/api/health'){await env.DB.prepare('SELECT 1').first();return J({ok:true,database:'connected',company:'SDE'});}
if(u.pathname==='/api/dashboard'){const d=await env.DB.prepare(`SELECT d.device_id,d.name,d.room,d.status,d.mode,d.target_temp,r.temperature,r.humidity,r.co2,r.recorded_at FROM devices d LEFT JOIN sensor_readings r ON r.id=(SELECT id FROM sensor_readings x WHERE x.device_id=d.device_id ORDER BY x.id DESC LIMIT 1) ORDER BY d.id`).all();const h=await env.DB.prepare(`SELECT temperature,humidity,co2,recorded_at FROM sensor_readings WHERE recorded_at>=datetime('now','-24 hours') ORDER BY recorded_at`).all();const s=await env.DB.prepare(`SELECT ROUND(AVG(temperature),1) temperature,ROUND(AVG(humidity),0) humidity,ROUND(AVG(co2),0) co2 FROM sensor_readings WHERE recorded_at>=datetime('now','-24 hours')`).first();return J({company:'SDE',summary:s,devices:d.results.map(clean),readings:h.results});}
const hist=u.pathname.match(/^\/api\/devices\/([^/]+)\/history$/);if(hist){const hours=Math.min(Math.max(Number(u.searchParams.get('hours')||24),1),168);const r=await env.DB.prepare(`SELECT temperature,humidity,co2,recorded_at FROM sensor_readings WHERE device_id=? AND recorded_at>=datetime('now',?) ORDER BY recorded_at`).bind(hist[1],`-${hours} hours`).all();return J(r.results);}
const dev=u.pathname.match(/^\/api\/devices\/([^/]+)$/);if(dev&&req.method==='PATCH'){const b=await req.json(),f=[],v=[];if(b.mode!==undefined){f.push('mode=?');v.push(b.mode)}if(b.target_temp!==undefined){f.push('target_temp=?');v.push(Number(b.target_temp))}if(b.status!==undefined){f.push('status=?');v.push(b.status)}if(!f.length)return J({error:'No editable fields'},400);v.push(dev[1]);await env.DB.prepare(`UPDATE devices SET ${f.join(',')} WHERE device_id=?`).bind(...v).run();return J(clean(await latest(env.DB,dev[1])))}
if(u.pathname==='/api/sensors'&&req.method==='POST'){const b=await req.json();if(!b.device_id||b.temperature===undefined||b.humidity===undefined||b.co2===undefined)return J({error:'device_id, temperature, humidity and co2 are required'},400);if(!await env.DB.prepare('SELECT 1 FROM devices WHERE device_id=?').bind(b.device_id).first())return J({error:'Unknown device_id'},404);await env.DB.prepare(`INSERT INTO sensor_readings(device_id,temperature,humidity,co2,recorded_at) VALUES(?,?,?,?,COALESCE(?,datetime('now')))` ).bind(b.device_id,Number(b.temperature),Number(b.humidity),Number(b.co2),b.recorded_at||null).run();return J({ok:true,device_id:b.device_id});}
if(env.ASSETS)return env.ASSETS.fetch(req);return new Response('Not Found',{status:404});
}catch(e){return J({error:e.message},500)}}};
